version: '3.8'

services:
  plant-detector:
    image: devehab/plant-detector:latest  # Replace with your Docker Hub image
    container_name: plant-detector
    restart: unless-stopped
    ports:
      - "3000:3000"  # Expose the application on port 3000
    environment:
      - FLASK_ENV=production  # Example: Set environment variables if needed
      - FLASK_APP=app.py
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
